---
-
  hosts: db
  vars:
    db_password: password
  tasks:
    - name: move MariaDB
      become: yes 
      copy: src=db/MariaDB.repo dest=/etc/yum.repos.d/MariaDB.repo mode=0644  

    - name: MariaDB server present 
      become: yes
      yum: name=MariaDB-server,MariaDB-client update_cache=yes state=present

    - name: MariaDB enabled 
      become: yes
      service: name=mariadb state=started enabled=yes

    - name: move mariaDB andwers to different file
      template: src=db/mariadb_answers.txt dest=/tmp/mariadb_answers.txt mode=0644

    - name:  
      become: yes
      shell: /usr/bin/mysql_secure_installation </tmp/mariadb_answers.txt

    - name:  
      unarchive: src=db/db.tgz dest=~/ 

    - name: 
      command: ./make_databases.sh {{ db_password }} localhost chdir=~/db
      ignore_errors: True
