---
-
  hosts: db
  vars:
    db_password: password
  tasks:
    - name: 1
      become: yes
      copy: src=db/MariaDB.repo dest=/etc/yum.repos.d/MariaDB.repo mode=0644

    - name: 2
      become: yes
      yum: name=MariaDB-server,MariaDB-client update_cache=yes state=present

    - name: 3
      become: yes
      service: name=mariadb state=started enabled=yes

    - name: 4
      template: src=db/mariadb_answers.txt dest=/tmp/mariadb_answers.txt mode=0644

    - name: 5
      become: yes
      shell: /usr/bin/mysql_secure_installation </tmp/mariadb_answers.txt

    - name: 6
      unarchive: src=db/db.tgz dest=~/ mode=0755

    - name: 7
      command: ./make_databases.sh {{ db_password }} localhost chdir=~/db
      ignore_errors: True
