---
-
  hosts: db
  vars:
    db_password: password
  tasks:
    - name: Copy MariaDB
      become: yes
      copy: src=db/MariaDB.repo dest=/etc/yum.repos.d/MariaDB.repo mode=0644

    - name: Update MariaDB Client
      become: yes
      package: name=MariaDB-client update_cache=yes state=present

    - name: Unzip database files
      become: yes
      unarchive: src=db/db.tgz dest=~/ mode=0755

    - name: Run database script
      become: yes
      command: ./make_databases.sh {{ db_password }} weeb-man.ckf7cxro7bkn.us-west-2.rds.amazonaws.com chdir=~/db
      ignore_errors: True

