---
-
  hosts: db
  vars:
    db_password: password
  tasks:
    - name: 1
      become: yes
      copy: src=db/MariaDB.repo dest=/etc/yum.repos.d/MariaDB.repo mode=0644

    - name: 2
      become: yes
      yum: name=MariaDB-client update_cache=yes state=present

#    - name: 3
#      become: yes
#      service: name=mariadb state=started enabled=yes

#    - name: 4
#      become: true
#      copy: src=db/MariaDB.repo dest=/etc/yum.repos.d/MariaDB.repo mode=0644

#    - name: 5
#      become: yes
#      shell: /usr/bin/mysql_secure_installation </tmp/mariadb_answers.txt

    - name: 6
      become: true
      unarchive: src=db/db.tgz dest=~/ mode=0777

    - name: 7
      become: yes
      command: ./make_databases.sh "{{ db_password }}" weeb-man.ckf7cxro7bkn.us-west-2.rds.amazonaws.com:3306
      ignore_errors: True
