---
- hosts: web
  vars:
    db_password: password
    server_name: curriculum
    service_name: curriculum
    service_version: 1.0
    app_key: QujjaJs3fxwtnTl7FiqhEEn1ACkf7YZW
    app_env: test
    db_host: weeb-man.ckf7cxro7bkn.us-west-2.rds.amazonaws.com
    db_database: curriculum
    db_username: curriculum
    db_port: 3306
    service_dir: /usr/share/nginx/{{ service_name }}
    ansible_ssh_private_key_file: ~/.ssh/cit360.pem
  tasks:
    - name: Yum epel-release
      become: yes
      yum: name=epel-release update_cache=yes state=present

    - name: install newer php
      become: yes
      shell: yes | yum install php54 php54-fpm php54-ldap php54-mbstring php54-mcrypt php54-pdo

    - name: nginx installation
      become: yes
      yum: name=nginx update_cache=yes state=present
      register: nginx_install

    - name: Download composer
      become: yes
      get_url:
      url: https://getcomposer.org/installer
      dest: /usr/local/bin/composer
      mode: 0700

    - name: Install composer
      become: yes
      shell: php /usr/local/bin/composer --install-dir=/usr/local/bin --filename=composer

    - name: second nginx configuration
      become: yes
      copy: src=~/ansible/web/nginx.conf dest=/etc/nginx/nginx.conf mode=0000
      register: nginx_conf
	  
    - name: configure vhost_conf
      become: yes
      template: src=~/ansible/web/vhost.conf.j2 dest=/etc/nginx/conf.d/{{ service_name }}.conf mode=0644
      register: vhost_conf

    - name: register php_conf
      become: yes
      template: src=~/ansible/web/php.ini.j2 dest=/etc/php.ini mode=0644
      register: php_conf

    - name: register php_fpm_conf
      become: yes
      copy: src=~/ansible/web/php-fpm-web.conf dest=/etc/php-fpm.d/www.conf mode=0644
      register: php_fpm_conf

    - name: restart nginx
      become: yes
      service: name=nginx state=restarted enabled=yes
      when: nginx_install|changed or nginx_conf|changed or vhost_conf|changed

    - name: restart php-fpm
      become: yes
      service: name=php-fpm state=restarted enabled=yes
      when: nginx_install|changed or php_conf|changed or php_fpm_conf|changed

    - name: important misc
      become: yes
      file: path="{{ service_dir }}" state=directory
	
    - name: unarchive web
      become: yes
      unarchive: src=~/ansible/web/{{ service_name }}.tgz dest="{{ service_dir }}" mode=0755
          
    - name: misc composer
      become: yes
      command: /usr/local/bin/composer update chdir={{ service_dir }}
      ignore_errors: True
          
    - name: reset permissions
      become: yes
      file: recurse=yes path={{ service_dir }}/storage mode=0777
          
    - name: reset nginx permissions
      become: yes
      file: recurse=yes path={{ service_dir }} owner=nginx group=nginx
          
    - name: final applications
      become: yes
      template: src=~/ansible/web/env.j2 dest="{{ service_dir }}/.env" mode=0644 owner=nginx

